version: "3.9"

services:
  vaultwarden:
    image: ${VAULTWARDEN_IMAGE}
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "127.0.0.1:${VAULTWARDEN_HTTP_PORT}:80"
    environment:
      TZ: ${TZ}
      DOMAIN: ${VAULTWARDEN_DOMAIN}
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      # Opcional: cerrar registros desde ENV (también puedes hacerlo en /admin)
      SIGNUPS_ALLOWED: "false"

      # Límites y nivel de log
      RATE_LIMITS: ${RATE_LIMITS}
      LOG_LEVEL: ${LOG_LEVEL}

      # SMTP (opcional)
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      # Si necesitas adjuntos grandes:
      # ROCKET_LIMITS: {forms="128 MiB", data-form="128 MiB"}

    volumes:
      - ${VAULTWARDEN_BASE}/data:/data

networks:
  default:
    name: vaultwarden_net
# Prueba de modificación