version: "3.8"

services:
  vaultwarden:
    image: ${VAULTWARDEN_IMAGE}
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      DOMAIN: ${DOMAIN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      INVITATIONS_ALLOWED: ${INVITATIONS_ALLOWED}
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      ROCKET_LIMITS: ${ROCKET_LIMITS}
      # Recomendable en producción:
      LOG_FILE: /data/vaultwarden.log
      USE_SYSLOG: false
    ports:
      # Exponemos SOLO en loopback; DSM reverse proxy hará el front en 443
      - "127.0.0.1:${HOST_HTTP_PORT}:80"
    volumes:
      - "${VAULTWARDEN_DATA}:/data"
    security_opt:
      - no-new-privileges:true
    # Opcional: limitar recursos
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 512M
<<<<<<< HEAD

    
=======
>>>>>>> 2fd63d4 (Vaultwarden ajustes compose y .env.example)
