version: "3.9"
services:
vaultwarden:
image: ${VAULTWARDEN_IMAGE}
container_name: vaultwarden
restart: unless-stopped
# Desde v1.31+ WebSockets integrados en Rocket; no es necesario 3012
ports:
- "127.0.0.1:${VAULTWARDEN_HTTP_PORT}:80"
environment:
TZ: ${TZ}
DOMAIN: ${VAULTWARDEN_DOMAIN}
SIGNUPS_ALLOWED: "false"
ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
# Si necesitas subir adjuntos grandes
# ROCKET_LIMITS={forms="128 MiB", data-form="128 MiB"}
# SMTP opcional
# SMTP_HOST=smtp.tu-proveedor.tld
# SMTP_FROM=vw@docunube.com
# SMTP_PORT=587
# SMTP_SSL=true
# SMTP_USERNAME=usuario
# SMTP_PASSWORD=contraseña
volumes:
- ${VAULTWARDEN_BASE}/data:/data


networks:
default:
name: vaultwarden_net